version: "3.8"

services:

  web:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: django_app
    restart: always
    command: gunicorn -b 0.0.0.0:8000 config.wsgi
    depends_on:
      - redis
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - .:/code/
  
  channels:
    container_name: websocket
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: daphne -b 0.0.0.0 -p 9000 config.asgi:application
    expose:
      - 9000
    env_file:
      - ./.env
    links:
      - redis
    depends_on:
      - redis
      - web
      
  redis:
    image: redis
    restart: always
    container_name: redis
    
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    restart: always
  
  nginx:
    build: ./compose/nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - web
    volumes:
      - ./cryptocurrency_project/apps/static:/static
      - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  celery_beat:
    container_name: celery_beat
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: celery -A config beat --loglevel=INFO
    depends_on:
      - celery_worker
      - rabbitmq
      - redis
    env_file:
      - ./.env
    volumes:
      - ./cryptocurrency_project:/code/cryptocurrency_project
      
  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: celery -A config worker --loglevel=INFO
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - ./.env
    volumes:
      - ./cryptocurrency_project:/code/cryptocurrency_project